import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://sabpatakaro.com'
  
  // Static pages
  const staticPages = [
    '',
    '/about',
    '/contact',
    '/disclaimer',
    '/privacy-policy',
    '/terms-of-service',
    '/guides',
    '/passport',
    '/pan-card',
    '/aadhar',
    '/driving-license',
    '/term-insurance',
    '/term-insurance/best-plans',
    '/term-insurance/premium-calculator',
    '/term-insurance/how-much-cover',
    '/term-insurance/claim-settlement-ratio',
    '/term-insurance/riders',
    '/term-insurance/mistakes',
    '/term-insurance/for-salaried',
    '/term-insurance/for-self-employed',
    '/term-insurance/vs-traditional',
    '/health-insurance',
    '/health-insurance/best-plans',
    '/health-insurance/how-much-cover',
    '/health-insurance/for-parents-seniors',
    '/health-insurance/claim-process',
    '/health-insurance/cashless-network',
    '/health-insurance/waiting-period',
    '/health-insurance/copayment-sublimits',
    '/health-insurance/individual-vs-family-floater',
    '/health-insurance/premium-calculator',
    '/tax',
    '/tax/income-tax-slabs',
    '/tax/section-80c',
    '/tax/section-80d',
    '/tax/old-vs-new-regime',
    '/tax/income-tax-calculator',
    '/tax/best-tax-saving-options',
    '/tax/how-to-save-tax-legally',
    '/tax/salary-tax-calculation',
    '/tax/mutual-funds-taxation',
    '/tax/capital-gains-shares',
    '/tax/short-vs-long-term-capital-gains',
    '/investing',
    '/investing/what-is-sip',
    '/investing/sip-vs-lumpsum',
    '/investing/best-mutual-funds-beginners',
    '/investing/emergency-fund',
    '/investing/retirement-planning',
    '/investing/retirement-calculator',
    '/investing/common-mistakes',
    '/investing/how-much-to-save',
    '/investing/start-investing-small',
    '/tools/sip-return-calculator',
    '/tools/emi-calculator',
    '/tools/term-coverage-calculator',
    '/tools/compare-term-insurance',
    '/tools/health-coverage-estimator',
    '/tools/compare-health-insurance',
    '/tools/tax-saving-planner',
    '/tools/financial-health-check',
  ]

  return staticPages.map((page) => ({
    url: `${baseUrl}${page}`,
    lastModified: new Date(),
    changeFrequency: page === '' ? 'daily' : 'weekly',
    priority: page === '' ? 1 : page.split('/').length === 2 ? 0.9 : 0.8,
  }))
}
